name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # نخليو Gradle/التوقيع يقرى الباسوردات من الـenv
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages (platform 34 + build-tools)
        run: sdkmanager "platforms;android-34" "build-tools;30.0.3"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # نفكّ الملف من السرّ BASE64 باش يلقاه Gradle فـ ${rootDir}/release-keystore.jks
      - name: Restore keystore from BASE64 secret
        shell: bash
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release-keystore.jks
          ls -l release-keystore.jks

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # بنِّي Release موقّع (بدّل :app: إذا كان اسم الموديول مختلف)
      - name: Build signed APK & AAB
        run: |
          gradle :app:clean
          gradle :app:assembleRelease
          gradle :app:bundleRelease

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: signed-release-outputs
          path: |
            app/build/outputs/apk/release/*release*.apk
            app/build/outputs/bundle/release/*release*.aab
