name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # رجّع ملف keystore من السر BASE64
      - name: Restore keystore (from BASE64)
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release-keystore.jks
          ls -l release-keystore.jks

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # ⚠️ هنا كنمرّرو كلمات السر والـ alias كـ ENV
      - name: Build Release (APK + AAB)
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          gradle :app:clean
          gradle :app:assembleRelease
          gradle :app:bundleRelease

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-outputs
          path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
