name: Generate Android Keystore
on:
  workflow_dispatch:

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate keystore (Masafir / Reda@22saif33)
        run: |
          keytool -genkeypair -v \
            -keystore release-keystore.jks \
            -storepass "Reda@22saif33" \
            -keypass "Reda@22saif33" \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -alias Masafir \
            -dname "CN=Masafir, OU=Dev, O=Masafir, L=City, S=State, C=MA"

      - name: Encode Keystore to Base64 (single line)
        run: |
          base64 -w0 release-keystore.jks > keystore.b64
          echo "DONE"

      - name: Upload Keystore Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: keystore-artifacts
          path: |
            keystore.b64
            release-keystore.jks
