name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages (platform 34 + build-tools)
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # كنستعمل Gradle بلا wrapper
      - name: Build Debug APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: :app:assembleDebug

      - name: Upload Debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      # اختياري: بْنِي AAB ديال الريليز غير موقّع
      - name: Build Release AAB (unsigned)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: :app:bundleRelease

      - name: Upload Release AAB
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app/build/outputs/bundle/release/*.aab
