name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # نوصلو كلمات السر للـ Gradle عبر ENV
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Restore keystore from BASE64
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release-keystore.jks
          ls -lh release-keystore.jks

      - name: Setup Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Build Release (APK & AAB)
        run: |
          ./gradlew :app:assembleRelease
          ./gradlew :app:bundleRelease

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-outputs
          path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
