name: Diagnose Keystore

on:
  workflow_dispatch:

jobs:
  diag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore keystore from BASE64
        run: |
          printf "%s" "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release-keystore.jks
          ls -lh release-keystore.jks

      - name: Check keystore password
        run: |
          keytool -list -keystore release-keystore.jks \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" || exit 1

      - name: Show alias(es)
        run: |
          keytool -list -keystore release-keystore.jks \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" | grep "Alias name"

      - name: Check key password
        run: |
          keytool -keypasswd -keystore release-keystore.jks \
            -alias "${{ secrets.KEY_ALIAS }}" \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.KEY_PASSWORD }}" -new "${{ secrets.KEY_PASSWORD }}" || exit 1
