name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # نثبتو Gradle بلا Wrapper
      - name: Set up Gradle (no wrapper)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Build Debug APK
        run: gradle :app:assembleDebug

      - name: Build Release AAB (unsigned)
        run: gradle :app:bundleRelease

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: app/build/outputs/bundle/release/*.aab
