name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # نوفر متغيرات البيئة من الـ secrets
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD:     ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS:        ${{ secrets.KEY_ALIAS }}

    steps:
      # 1) جِبّ الكود
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) إعداد Android SDK (اختياري ولكن مفيد لبعض المهام)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 3) إعداد JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 4) رجّع keystore من Base64 إلى ملف فعلي داخل app/release-keystore.jks
      - name: Restore keystore from BASE64
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > app/release-keystore.jks
          ls -lh app/release-keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      # (اختياري) تشديد صلاحيات الملف
      - name: Secure keystore permissions
        run: chmod 600 app/release-keystore.jks

      # 5) إعداد Gradle 8.8 (ضروري باش نواكب متطلبات Target/SDK الحديثة)
      - name: Setup Gradle 8.8
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.8

      # 6) بناء Debug (اختياري — يساعد نتأكد أن كلشي خدام)
      - name: Build Debug APK
        run: gradle :app:assembleDebug --stacktrace

      # 7) بناء Release (APK & AAB)
      - name: Build Release (APK & AAB)
        run: |
          gradle :app:assembleRelease --stacktrace
          gradle :app:bundleRelease   --stacktrace

      # 8) رفع المخرجات كـ artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-outputs
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
