name: Android CI (Signed AAB)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Java 17 (AGP 8.x)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # (اختياري) تقدر تحذف خطوة التحقق من الـ wrapper إذا ما عندكش gradle-wrapper.jar
      # - name: Validate Gradle Wrapper
      #   uses: gradle/actions/wrapper-validation@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # استرجاع keystore من الـ secrets (Base64 → ملف .jks)
      - name: Restore keystore from BASE64
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/release-keystore.jks
          ls -lh app/release-keystore.jks
          chmod 600 app/release-keystore.jks

      # نضيف خصائص التوقيع إلى gradle.properties (يُقرأ من build.gradle)
      - name: Configure signing properties
        run: |
          cat >> gradle.properties <<'EOF'
          MY_STORE_FILE=app/release-keystore.jks
          MY_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          MY_KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          MY_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
          EOF
          echo "gradle.properties updated"

      # Build Debug APK (للتجربة)
      - name: Assemble Debug APK
        run: ./gradlew :app:assembleDebug -S --warning-mode all

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      # Build Release AAB (مُوقّع بمفاتيحك)
      - name: Assemble Signed Release AAB
        run: ./gradlew :app:bundleRelease -S --warning-mode all

      - name: Upload Signed Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab-signed
          path: app/build/outputs/bundle/release/*.aab
