name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # نوفر الـ ENV ل Gradle (نفس الأسماء اللي فال secrets)
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # ⬇️ هادي أهم خطوة: نفكّو الـ Base64 ونحطّو الملف فـ app/release-keystore.jks
      - name: Restore keystore from BASE64
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > app/release-keystore.jks
          ls -lh app/release-keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      # (اختياري ولكن مزيان) نحذف صلاحيات القراءة للجميع
      - name: Secure keystore permissions
        run: chmod 600 app/release-keystore.jks

      # Gradle 8.7
      - name: Setup Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      # بناء Debug (اختياري)، يساعد للتأكد كلشي خدام
      - name: Build Debug APK
        run: gradle :app:assembleDebug

      # بناء Release (APK & AAB)
      - name: Build Release (APK & AAB)
        run: |
          gradle :app:assembleRelease
          gradle :app:bundleRelease

      # رفع المخرجات
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-outputs
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
