name: Generate New Keystore

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore release-keystore.jks \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.KEY_PASSWORD }}" \
            -alias "${{ secrets.KEY_ALIAS }}" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Masafir, OU=Dev, O=Masafir, L=Casa, ST=MA, C=MA"

      - name: Encode Keystore to Base64
        run: base64 -w0 release-keystore.jks > keystore.b64

      - name: Upload keystore files
        uses: actions/upload-artifact@v4
        with:
          name: keystore-files
          path: |
            release-keystore.jks
            keystore.b64
