name: Generate Android Keystore

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore release-keystore.jks \
            -storepass ${{ secrets.STORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            -alias ${{ secrets.KEY_ALIAS }} \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "${{ secrets.DNAME }}"

      - name: Encode Keystore to Base64
        run: base64 release-keystore.jks > keystore.b64

      - name: Upload Keystore Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: keystore-files
          path: |
            release-keystore.jks
            keystore.b64
