name: Show Keystore Alias

on:
  workflow_dispatch:

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Restore keystore from BASE64
        run: |
          printf "%s" "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release-keystore.jks
          ls -lh release-keystore.jks

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: List aliases (using store password)
        run: |
          set -e
          echo "Trying to list aliases..."
          keytool -list -v \
            -storetype JKS \
            -keystore release-keystore.jks \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}"
