name: Show Keystore Alias

on:
  workflow_dispatch:

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Restore keystore from BASE64
        run: |
          printf "%s" "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release-keystore.jks
          ls -lh release-keystore.jks

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: List aliases (try JKS then PKCS12)
        shell: bash
        run: |
          set -e
          echo "Trying JKS..."
          keytool -list -v \
            -keystore release-keystore.jks \
            -storetype JKS \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" || true

          echo "Trying PKCS12..."
          keytool -list -v \
            -keystore release-keystore.jks \
            -storetype PKCS12 \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}"
