name: Show Keystore Alias

on:
  workflow_dispatch:

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore keystore from BASE64
        run: |
          printf "%s" "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release-keystore.jks
          ls -lh release-keystore.jks

      - name: Install Java (for keytool)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: List aliases
        run: |
          keytool -list -v -keystore release-keystore.jks -storepass "${{ secrets.KEYSTORE_PASSWORD }}" | grep -E "Alias name|الاسم المستعار|Nombre de alias|Alias"
